"""Initial

Revision ID: c63544f62ecb
Revises: 
Create Date: 2022-07-10 19:54:14.295458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c63544f62ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__backup_methods'))
    )
    op.create_index(op.f('ix__backup_methods__method_name'), 'backup_methods', ['method_name'], unique=False)
    op.create_table('backup_statuses',
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED_TO_OBTAIN_MODEL', 'UNKNOWN_MODEL', 'BACKUP_FAILED', name='backup_status'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('backuped', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ip', name=op.f('pk__backup_statuses'))
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('method', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['method'], ['backup_methods.id'], name=op.f('fk__models__method__backup_methods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__models'))
    )
    op.create_index(op.f('ix__models__model'), 'models', ['model'], unique=False)
    op.create_table('special_switches',
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('method', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['method'], ['backup_methods.id'], name=op.f('fk__special_switches__method__backup_methods')),
    sa.PrimaryKeyConstraint('ip', name=op.f('pk__special_switches'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_switches')
    op.drop_table('models')
    op.drop_table('backup_statuses')
    op.drop_table('backup_methods')
    # ### end Alembic commands ###
